mingit: exclude the tzdata
Since https://github.com/msys2/MINGW-packages/pull/24750, the
`mingw-w64-gcc-libs` package now has a hard dependency on
`mingw-w64-tzdata`. That latter package contains, let's say, _many_
files.

As a consequence, the `7z` invocation to build MinGit would now fail
like this:

  Creating .zip archive
  + cd /
  + 7z a -mx9 [...]
  release.sh: line 176: /mingw64/bin/7z: Argument list too long
  Error: Process completed with exit code 126.

Since the new code that makes use of that tzdata explicitly comes with a
fall-back to an internal database, let's just skip the tzdata when
building MinGit.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>