nuget(mingit): handle `scalar.exe` properly
Even if the file is "both" in `mingw64/bin/` and in
`mingw64/libexec/git-core/`, it is actually the same file, and we simply
use one copy and ignore the other.

This fixes the following symptom, encountered in
https://dev.azure.com/git-for-windows/git/_build/results?buildId=106113&view=logs&j=18d122ab-b82e-5078-9335-b512275db2c9&t=7b2c60f3-bf2a-5119-a567-083de9ea7e75&l=20065:

	Attempting to build package from 'Git-Windows-Minimal.nuspec'.
	Error NU5050: Attempted to pack multiple files into the same location(s). The following destinations were used multiple times: tools\mingw64\bin\scalar.exe
	NuGet.Packaging.Core.PackagingException: Attempted to pack multiple files into the same location(s). The following destinations were used multiple times: tools\mingw64\bin\scalar.exe

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>